apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: denyreviewsv2handler
spec:
  status:
    code: 7
    message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denyreviewsv2request
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denyreviewsv2
spec:
  match: destination.labels["app"] == "ratings" && source.labels["app"]=="reviews" && source.labels["version"] == "v2"
  actions:
  - handler: denyreviewsv2handler.denier
    instances: [ denyreviewsv2request.checknothing ]